[package]
name = "pict-rs"
description = "A simple image hosting service"
version = "0.3.0-alpha.12"
authors = ["asonix <asonix@asonix.dog>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://git.asonix.dog/asonix/pict-rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-form-data = "0.6.0-beta.1"
actix-fs = { git = "https://git.asonix.dog/asonix/actix-fs", branch = "asonix/actix-rt-2" }
actix-rt = "2.2.0"
actix-web = { version = "4.0.0-beta.8", default-features = false }
anyhow = "1.0"
async-stream = "0.3.0"
awc = { version = "3.0.0-beta.7", default-features = false }
base64 = "0.13.0"
futures = "0.3.4"
magick_rust = { version = "0.15.0" }
mime = "0.3.1"
num_cpus = "1"
once_cell = "1.4.0"
rand = "0.8.0"
rexiv2 = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.0"
sled = { version = "0.34.6" }
structopt = "0.3.14"
thiserror = "1.0"
time = { version = "0.2.23", features = ["serde"] }
tokio = { version = "1", default-features = false, features = ["sync", "process"] }
tracing = "0.1.15"
tracing-futures = "0.2.4"
tracing-subscriber = { version = "0.2.5", features = ["fmt", "tracing-log"] }
uuid = { version = "0.8", features = ["v4"] }

[dependencies.ffmpeg-next]
version = "4.4.0-dev"
default-features = false
features = ["codec", "filter", "device", "format", "resampling", "postprocessing", "software-resampling", "software-scaling"]
git = "https://github.com/jwiesler/rust-ffmpeg"

[dependencies.ffmpeg-sys-next]
version = "4.3.5"
git = "https://github.com/jwiesler/rust-ffmpeg-sys"
