version: '3.3'

services:
  pictrs:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: "${USER_ID:-1000}"
        GID: "${GROUP_ID:-1000}"
    ports:
      - "8080:8080"
    links:
      - "minio:pict-rs.minio"
    stdin_open: true
    tty: true
    volumes:
      - ./storage/pict-rs:/mnt
      - ../../:/opt/app

  pictrs_proxy:
    image: asonix/pictrs-proxy:latest
    ports:
      - "8081:8081"
    environment:
      - PICTRS_PROXY_UPSTREAM=http://pictrs:8080

  minio:
    image: quay.io/minio/minio
    command: server /mnt --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/mnt
