[server]
address = '0.0.0.0:8080'
worker_id = 'pict-rs-1'

[tracing.logging]
format = 'normal'
targets = 'warn,tracing_actix_web=info,actix_server=info,actix_web=info'

[tracing.console]
buffer_capacity = 102400

[tracing.opentelemetry]
service_name = 'pict-rs'
targets = 'info'

[old_db]
path = '/mnt'

[media]
max_width = 10000
max_height = 10000
max_area = 40000000
max_file_size = 40
enable_silent_video = true
enable_full_video = true
filters = ['blur', 'crop', 'identity', 'resize', 'thumbnail']
skip_validate_imports = false

[repo]
type = 'sled'
path = '/mnt/sled-repo'
cache_capacity = 67108864

[store]
type = 'object_storage'
endpoint = 'http://minio:9000'
use_path_style = true
bucket_name = 'pict-rs'
region = 'minio'
access_key = 'pictrs'
secret_key = 'pictrspass'
