path = '/mnt'
addr = '0.0.0.0:8080'

[store]
type = 's3_store'
bucket_name = 'pict-rs'
region = 'http://minio:9000'
access_key = 'XZEZ5B8Y3UCINU1KCVF6'
secret_key = 'cWbE5LcCK9YH8j1NvhOZocl+vH+b6T5Zvy3z+BZu'
