path = 'data/'
addr = '0.0.0.0:8080'

repo = 'sled'
store = 'object_storage'

[sled]
sled_cache_capacity = 67108864

[filesystem_storage]
filesystem_storage_path = '/mnt/files'

[object_storage]
object_store_bucket_name = 'pict-rs'
object_store_region = 'http://minio:9000'
object_store_access_key = 'XZEZ5B8Y3UCINU1KCVF6'
object_store_secret_key = 'cWbE5LcCK9YH8j1NvhOZocl+vH+b6T5Zvy3z+BZu'
