path = '/mnt'
addr = '0.0.0.0:8080'

[store]
type = 's3_store'
bucket_name = 'pict-rs'
region = 'http://minio:9000'
access_key = 'Q7Z3AY3JO01N27UNH5IR'
secret_key = 'bH3Kj6UVJF+btBtWsExVurN3ukEilC3saECsupzi'
